### ISSUE TITLE
While Execute got an error

### ISSUE THREAD

**Issue by WorldOfDex** [bunnykek/F-Lyrics#3]
Traceback (most recent call last):
  File "D:\Tool\F-Lyrics\flyrics.py", line 54, in <module>
    module.Lyrics(url, api=False)
  File "D:\Tool\F-Lyrics\modules\spotify.py", line 75, in __init__
    self.jsonResponse = [self.getTrackLyrics(id_, api)]
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Tool\F-Lyrics\modules\spotify.py", line 121, in getTrackLyrics
    lines = response.json()['lyrics']['lines']
            ^^^^^^^^^^^^^^^
  File "C:\Users\DEX\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEX\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEX\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEX\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0) why?

**Comment by bunnykek** [comment]
Updated. Try now. Make sure to add spotify auth bearer token in the config file.

**Comment by WorldOfDex** [comment]
HOW TO GET BEARED TOKEN ? I HAVE ONLY CLIENT ID AND CLIENCT SECRET CODE

**Comment by vmiyoshi** [comment]
I don't think this works anymore, 
I did add the spotify auth bearer token I generated using a python script created using these scopes 

SCOPES = (
    "user-read-private user-read-email "
    "user-library-read user-library-modify "
    "user-read-playback-state user-modify-playback-state "
    "user-read-currently-playing user-read-recently-played "
    "user-top-read playlist-read-private playlist-read-collaborative "
    "playlist-modify-public playlist-modify-private"
)

I think spotify may have made some changes and generating a token is more difficult then it use to be in years past...

```
  },
    "spotify": {
        "auth_bearer": "Bearer BQBVP-eE....
```

```
Spotify URL detected.
Fetching the lyrics...
Traceback (most recent call last):
  File "/Users/user/F-Lyrics/flyrics.py", line 54, in <module>
    module.Lyrics(url, api=False)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/Users/user/F-Lyrics/modules/spotify.py", line 84, in __init__
    self.jsonResponse = [self.getTrackLyrics(id_, api)]
                         ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/Users/user/F-Lyrics/modules/spotify.py", line 130, in getTrackLyrics
    lines = response.json()['lyrics']['lines']
            ~~~~~~~~~~~~~^^
  File "/Users/user/F-Lyrics/venv/lib/python3.13/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/json/decoder.py", line 345, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/json/decoder.py", line 363, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by bunnykek** [comment]
Yeah, I need to fix this script, its been a long since i tested it.

**Comment by bunnykek** [comment]
Try now. I have fixed all of the modules.
